# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QLayout, QLineEdit, QPushButton,
    QSizePolicy, QToolBox, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(559, 847)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(11)
        Form.setFont(font)
        Form.setLayoutDirection(Qt.LeftToRight)
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 20, 91, 31))
        self.label.setFont(font)
        self.hw_start = QPushButton(Form)
        self.hw_start.setObjectName(u"hw_start")
        self.hw_start.setGeometry(QRect(80, 790, 121, 31))
        self.label_71 = QLabel(Form)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(30, 60, 71, 31))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_71.sizePolicy().hasHeightForWidth())
        self.label_71.setSizePolicy(sizePolicy1)
        self.label_71.setFont(font)
        self.Authen = QComboBox(Form)
        self.Authen.setObjectName(u"Authen")
        self.Authen.setGeometry(QRect(120, 60, 131, 31))
        self.hw_save = QPushButton(Form)
        self.hw_save.setObjectName(u"hw_save")
        self.hw_save.setGeometry(QRect(380, 790, 121, 31))
        self.iface = QComboBox(Form)
        self.iface.setObjectName(u"iface")
        self.iface.setGeometry(QRect(120, 20, 401, 31))
        self.User = QLineEdit(Form)
        self.User.setObjectName(u"User")
        self.User.setGeometry(QRect(120, 100, 131, 31))
        self.Pwd = QLineEdit(Form)
        self.Pwd.setObjectName(u"Pwd")
        self.Pwd.setGeometry(QRect(300, 100, 111, 31))
        self.label_73 = QLabel(Form)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(70, 100, 51, 31))
        self.label_99 = QLabel(Form)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(30, 100, 41, 31))
        self.label_76 = QLabel(Form)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(30, 140, 61, 31))
        self.hw_smac = QLineEdit(Form)
        self.hw_smac.setObjectName(u"hw_smac")
        self.hw_smac.setGeometry(QRect(120, 140, 311, 31))
        self.label_67 = QLabel(Form)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(30, 180, 81, 31))
        self.label_67.setFont(font)
        self.hw_sername = QLineEdit(Form)
        self.hw_sername.setObjectName(u"hw_sername")
        self.hw_sername.setGeometry(QRect(120, 180, 131, 31))
        self.label_100 = QLabel(Form)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setGeometry(QRect(30, 210, 71, 51))
        self.ac_name = QLineEdit(Form)
        self.ac_name.setObjectName(u"ac_name")
        self.ac_name.setGeometry(QRect(120, 220, 131, 31))
        self.label_68 = QLabel(Form)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(270, 110, 20, 21))
        self.toolBox = QToolBox(Form)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setGeometry(QRect(20, 260, 511, 511))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(0, 0, 511, 453))
        self.hw_dns2 = QLineEdit(self.page)
        self.hw_dns2.setObjectName(u"hw_dns2")
        self.hw_dns2.setGeometry(QRect(270, 90, 141, 31))
        self.label_62 = QLabel(self.page)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(10, 90, 51, 31))
        self.label_62.setFont(font)
        self.hw_dns1 = QLineEdit(self.page)
        self.hw_dns1.setObjectName(u"hw_dns1")
        self.hw_dns1.setGeometry(QRect(100, 90, 141, 31))
        self.label_66 = QLabel(self.page)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(250, 100, 20, 21))
        self.hw_server = QLineEdit(self.page)
        self.hw_server.setObjectName(u"hw_server")
        self.hw_server.setGeometry(QRect(100, 40, 141, 31))
        self.label_64 = QLabel(self.page)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(10, 40, 71, 31))
        self.label_64.setFont(font)
        self.hw_serip = QLineEdit(self.page)
        self.hw_serip.setObjectName(u"hw_serip")
        self.hw_serip.setGeometry(QRect(360, 40, 121, 31))
        self.label_65 = QLabel(self.page)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(270, 40, 51, 31))
        self.label_65.setFont(font)
        self.groupBox_2 = QGroupBox(self.page)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(-10, 310, 491, 151))
        font1 = QFont()
        font1.setPointSize(9)
        self.groupBox_2.setFont(font1)
        self.label_57 = QLabel(self.groupBox_2)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(20, 10, 51, 41))
        self.label_57.setFont(font)
        self.hw_ver = QLineEdit(self.groupBox_2)
        self.hw_ver.setObjectName(u"hw_ver")
        self.hw_ver.setGeometry(QRect(110, 20, 141, 31))
        self.hw_code = QLineEdit(self.groupBox_2)
        self.hw_code.setObjectName(u"hw_code")
        self.hw_code.setGeometry(QRect(110, 60, 141, 31))
        self.label_58 = QLabel(self.groupBox_2)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(20, 60, 51, 31))
        self.label_58.setFont(font)
        self.hw_type = QLineEdit(self.groupBox_2)
        self.hw_type.setObjectName(u"hw_type")
        self.hw_type.setGeometry(QRect(370, 20, 121, 31))
        self.label_59 = QLabel(self.groupBox_2)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(280, 20, 61, 31))
        self.pro_rayload = QLineEdit(self.groupBox_2)
        self.pro_rayload.setObjectName(u"pro_rayload")
        self.pro_rayload.setGeometry(QRect(370, 60, 121, 31))
        self.label_60 = QLabel(self.groupBox_2)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(280, 60, 61, 31))
        self.label_60.setFont(font)
        self.hw_session_id = QLineEdit(self.groupBox_2)
        self.hw_session_id.setObjectName(u"hw_session_id")
        self.hw_session_id.setGeometry(QRect(110, 100, 141, 31))
        self.label_61 = QLabel(self.groupBox_2)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(20, 100, 81, 31))
        self.label_61.setFont(font)
        self.label_63 = QLabel(self.groupBox_2)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(280, 100, 61, 31))
        self.label_63.setFont(font)
        self.hw_tag = QLineEdit(self.groupBox_2)
        self.hw_tag.setObjectName(u"hw_tag")
        self.hw_tag.setGeometry(QRect(370, 100, 121, 31))
        self.groupBox = QGroupBox(self.page)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(-10, 140, 491, 171))
        self.label_78 = QLabel(self.groupBox)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(20, 10, 71, 31))
        self.check_pkt = QComboBox(self.groupBox)
        self.check_pkt.setObjectName(u"check_pkt")
        self.check_pkt.setGeometry(QRect(110, 10, 141, 31))
        self.label_77 = QLabel(self.groupBox)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(20, 50, 71, 31))
        self.lcp_op = QComboBox(self.groupBox)
        self.lcp_op.setObjectName(u"lcp_op")
        self.lcp_op.setGeometry(QRect(110, 50, 141, 31))
        self.hw_reply = QComboBox(self.groupBox)
        self.hw_reply.setObjectName(u"hw_reply")
        self.hw_reply.setGeometry(QRect(370, 10, 121, 31))
        self.label_72 = QLabel(self.groupBox)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(280, 10, 61, 31))
        self.label_72.setFont(font)
        self.wait_echoreq = QLineEdit(self.groupBox)
        self.wait_echoreq.setObjectName(u"wait_echoreq")
        self.wait_echoreq.setGeometry(QRect(110, 90, 141, 31))
        self.label_69 = QLabel(self.groupBox)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(20, 90, 81, 31))
        self.label_75 = QLabel(self.groupBox)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(280, 50, 81, 31))
        self.send_pack = QComboBox(self.groupBox)
        self.send_pack.setObjectName(u"send_pack")
        self.send_pack.setGeometry(QRect(370, 50, 121, 31))
        self.ser_error = QComboBox(self.groupBox)
        self.ser_error.setObjectName(u"ser_error")
        self.ser_error.setGeometry(QRect(370, 90, 121, 31))
        self.label_70 = QLabel(self.groupBox)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(280, 90, 61, 31))
        self.label_74 = QLabel(self.groupBox)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(20, 120, 81, 51))
        self.hw_mppe = QComboBox(self.groupBox)
        self.hw_mppe.setObjectName(u"hw_mppe")
        self.hw_mppe.setGeometry(QRect(110, 130, 141, 31))
        self.V4Support = QCheckBox(self.page)
        self.V4Support.setObjectName(u"V4Support")
        self.V4Support.setGeometry(QRect(10, 0, 141, 31))
        self.V4Support.setChecked(True)
        self.toolBox.addItem(self.page, u"IPv4\u914d\u7f6e")
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 511, 453))
        self.V6Support = QCheckBox(self.page_2)
        self.V6Support.setObjectName(u"V6Support")
        self.V6Support.setGeometry(QRect(10, 0, 141, 31))
        self.V6Support.setChecked(False)
        self.Support_method = QComboBox(self.page_2)
        self.Support_method.setObjectName(u"Support_method")
        self.Support_method.setGeometry(QRect(180, 0, 151, 31))
        self.label_79 = QLabel(self.page_2)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(10, 50, 81, 31))
        self.label_79.setFont(font)
        self.RemoteIp = QLineEdit(self.page_2)
        self.RemoteIp.setObjectName(u"RemoteIp")
        self.RemoteIp.setGeometry(QRect(130, 50, 121, 31))
        self.label_80 = QLabel(self.page_2)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(10, 90, 91, 31))
        self.label_80.setFont(font)
        self.label_81 = QLabel(self.page_2)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(10, 130, 91, 31))
        self.label_81.setFont(font)
        self.label_82 = QLabel(self.page_2)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(10, 170, 91, 31))
        self.label_82.setFont(font)
        self.Ipv6Prefix = QLineEdit(self.page_2)
        self.Ipv6Prefix.setObjectName(u"Ipv6Prefix")
        self.Ipv6Prefix.setGeometry(QRect(130, 90, 121, 31))
        self.DnsServer = QLineEdit(self.page_2)
        self.DnsServer.setObjectName(u"DnsServer")
        self.DnsServer.setGeometry(QRect(130, 130, 121, 31))
        self.Domain = QLineEdit(self.page_2)
        self.Domain.setObjectName(u"Domain")
        self.Domain.setGeometry(QRect(130, 170, 121, 31))
        self.toolBox.addItem(self.page_2, u"IPv6\u914d\u7f6e")

        self.retranslateUi(Form)

        self.toolBox.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u9009\u62e9\u7f51\u5361", None))
        self.hw_start.setText(QCoreApplication.translate("Form", u"\u5f00\u542f\u670d\u52a1", None))
        self.label_71.setText(QCoreApplication.translate("Form", u"\u8ba4\u8bc1\u65b9\u5f0f", None))
        self.hw_save.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58\u914d\u7f6e", None))
        self.User.setText(QCoreApplication.translate("Form", u"test", None))
        self.Pwd.setText(QCoreApplication.translate("Form", u"test", None))
        self.label_73.setText(QCoreApplication.translate("Form", u"\u5bc6\u7801", None))
        self.label_99.setText(QCoreApplication.translate("Form", u"\u8d26\u53f7-", None))
        self.label_76.setText(QCoreApplication.translate("Form", u"Ser_Mac", None))
        self.hw_smac.setText("")
        self.label_67.setText(QCoreApplication.translate("Form", u"Ser_name", None))
        self.hw_sername.setText(QCoreApplication.translate("Form", u"ac_server", None))
        self.label_100.setText(QCoreApplication.translate("Form", u"Ac_name", None))
        self.ac_name.setText(QCoreApplication.translate("Form", u"acname-test", None))
        self.label_68.setText(QCoreApplication.translate("Form", u"\u2014", None))
        self.hw_dns2.setText(QCoreApplication.translate("Form", u"8.8.8.8", None))
        self.label_62.setText(QCoreApplication.translate("Form", u"DNS", None))
        self.hw_dns1.setText(QCoreApplication.translate("Form", u"192.168.11.1", None))
        self.label_66.setText(QCoreApplication.translate("Form", u",", None))
        self.hw_server.setText(QCoreApplication.translate("Form", u"192.168.11.1", None))
        self.label_64.setText(QCoreApplication.translate("Form", u"Ser_Ip", None))
        self.hw_serip.setText(QCoreApplication.translate("Form", u"192.168.11.10", None))
        self.label_65.setText(QCoreApplication.translate("Form", u"\u5206\u914dIP", None))
        self.groupBox_2.setTitle("")
        self.label_57.setText(QCoreApplication.translate("Form", u"VER", None))
        self.hw_ver.setText(QCoreApplication.translate("Form", u"0x01", None))
        self.hw_code.setText(QCoreApplication.translate("Form", u" --", None))
        self.label_58.setText(QCoreApplication.translate("Form", u"CODE", None))
        self.hw_type.setText(QCoreApplication.translate("Form", u"0x01", None))
        self.label_59.setText(QCoreApplication.translate("Form", u"TYPE", None))
        self.pro_rayload.setText(QCoreApplication.translate("Form", u" --", None))
        self.label_60.setText(QCoreApplication.translate("Form", u"Payload", None))
        self.hw_session_id.setText(QCoreApplication.translate("Form", u"0x0000", None))
        self.label_61.setText(QCoreApplication.translate("Form", u"SessionId", None))
        self.label_63.setText(QCoreApplication.translate("Form", u"Tag", None))
        self.hw_tag.setText(QCoreApplication.translate("Form", u" --", None))
        self.label_78.setText(QCoreApplication.translate("Form", u"Options", None))
        self.label_77.setText(QCoreApplication.translate("Form", u"\u4fdd\u5b58\u62a5\u6587", None))
        self.label_72.setText(QCoreApplication.translate("Form", u"\u4e0d\u56de\u5e94", None))
        self.wait_echoreq.setText(QCoreApplication.translate("Form", u" --", None))
        self.label_69.setText(QCoreApplication.translate("Form", u"Echo+time", None))
        self.label_75.setText(QCoreApplication.translate("Form", u"Send_pack", None))
        self.label_70.setText(QCoreApplication.translate("Form", u"Ser\u5f02\u5e38", None))
        self.label_74.setText(QCoreApplication.translate("Form", u"MPPE\u52a0\u5bc6", None))
        self.V4Support.setText(QCoreApplication.translate("Form", u"PPPoEv4 Support", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QCoreApplication.translate("Form", u"IPv4\u914d\u7f6e", None))
        self.V6Support.setText(QCoreApplication.translate("Form", u"PPPoEv6 Support", None))
        self.label_79.setText(QCoreApplication.translate("Form", u"IPv6-Ip", None))
        self.RemoteIp.setText(QCoreApplication.translate("Form", u"2013::100", None))
        self.label_80.setText(QCoreApplication.translate("Form", u"Prefix", None))
        self.label_81.setText(QCoreApplication.translate("Form", u"Dns-Server", None))
        self.label_82.setText(QCoreApplication.translate("Form", u"Dns-Domain", None))
        self.Ipv6Prefix.setText(QCoreApplication.translate("Form", u"2013::", None))
        self.DnsServer.setText(QCoreApplication.translate("Form", u"2013::2", None))
        self.Domain.setText(QCoreApplication.translate("Form", u"ibm.com", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("Form", u"IPv6\u914d\u7f6e", None))
    # retranslateUi

